### ISSUE TITLE
add support for xiaomi.gateway.hub1

### ISSUE THREAD

**Issue by zy2688** [zy2688/hass-xiaomi-miot#4]
About PR #3 

能发布虚拟事件，但目前没法监听
```yaml
service: xiaomi_miot.call_action
data:
  throw: true
  entity_id: sensor.xiaomi_hub1_xxxx_gateway
  aiid: 1
  siid: 4
  params: 测试接收触发事件
```
